sudo: required

language: python
python:
  - "3.6.4"
cache: pip

services:
  - docker

install:
  - docker build --cache-from=infrastructureplayground/django:latest -t infrastructureplayground/django:latest .
  - docker network create backend_network
  - docker run -d --name=postgres
    --env POSTGRES_USER=playground
    --env POSTGRES_PASSWORD=playground
    --env POSTGRES_DB=playground
    --env POSTGRES_PORT=5432
    --env POSTGRES_SERVICE=postgres
    --env TZ=Asia/Singapore
    --network=backend_network
    unnotech/postgres-replication:10.4
  - docker run -d
    --name=django
    --env POSTGRES_USER=playground
    --env POSTGRES_PASSWORD=playground
    --env POSTGRES_DB=playground
    --env POSTGRES_PORT=5432
    --env POSTGRES_SERVICE=postgres
    --env DOCKERIZED=true
    --env TZ=Asia/Singapore
    --network=backend_network
    infrastructureplayground/django:latest

jobs:
  include:
    - stage: Authentication Unit Testing
      script: docker exec -it django
              coverage run --source='.'
              manage.py test authentication.tests.test_register
              &&
              docker exec -it django coverage report
    - script: docker exec -it django
              coverage run --source='.'
              manage.py test authentication.tests.test_login
              &&
              docker exec -it django coverage report
    - stage: Inventory Unit Testing
      script: docker exec -it django
              coverage run --source='.'
              manage.py test inventory.tests.BooksTest
              &&
              docker exec -it django coverage report