# Generated by Django 2.0.7 on 2018-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_published',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
