# Generated by Django 2.0.7 on 2020-03-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
    ]
